/**
 * Visualisations are *generated by running the real algorithm*, never authored
 * by hand.
 *
 * The same rule that governs lesson output governs these: a hand-drawn
 * animation of merge sort is a drawing of what somebody remembers merge sort
 * doing, and it will be subtly wrong in exactly the places a learner is trying
 * to understand. So every generator below is an ordinary implementation with
 * `emit()` calls threaded through it — the frames are a side effect of the
 * algorithm actually executing, and if the implementation is wrong the
 * animation is visibly wrong too.
 *
 * A frame is a complete snapshot rather than a delta. That costs memory on a
 * large input and buys the thing a learner needs most: the ability to step
 * *backwards*, which a delta stream cannot do without replaying from the start.
 */

/** What a highlighted cell means. Rendering maps these to colours. */
export type Role =
  | "compare"
  | "swap"
  | "pivot"
  | "sorted"
  | "active"
  | "window"
  | "discarded"
  | "found"
  /* The React track's roles. Reconciliation has its own vocabulary — a node is
     kept, updated in place, moved, created or destroyed — and borrowing
     "swapping" or "in final place" for those would put the wrong word in the
     legend under the animation. */
  | "mounted"
  | "updated"
  | "unchanged"
  | "unmounted"
  | "moved"
  /* Project layout has its own two. A file that did not exist before is
     "created", not "mounted" — mounting is something React does to a component,
     and a legend that said so under a directory listing would be teaching the
     wrong word at the moment the reader is looking for the right one. */
  | "created"
  | "deleted";

export interface ArrayFrame {
  kind: "array";
  values: number[];
  /** Index → role. Absent indices render as neutral. */
  roles: Record<number, Role>;
  /** One sentence saying what this step did. Also the screen-reader text. */
  note: string;
  /** Running tallies shown beside the animation. */
  stats?: Record<string, number>;
  /** Optional bracket labels drawn under ranges, e.g. `lo`, `hi`, `mid`. */
  markers?: Record<number, string>;
}

export interface TreeNode {
  id: string;
  label: string;
  /** Depth from the root, and horizontal slot — the layout is computed here
   *  rather than in the component so that a frame is fully self-describing. */
  depth: number;
  x: number;
  role?: Role;
  parent?: string;
  /** Trie nodes that terminate a word are drawn differently. */
  terminal?: boolean;
  /**
   * A short caption under the node.
   *
   * A React element tree needs to show each child's `key` beside it, since the
   * whole of reconciliation turns on those; the node circle itself only has
   * room for the element's type.
   */
  badge?: string;
}

export interface TreeFrame {
  kind: "tree";
  nodes: TreeNode[];
  note: string;
  stats?: Record<string, number>;
}

export interface SequenceItem {
  id: string;
  label: string;
  role?: Role;
}

/** Stacks, queues and linked lists: an ordered run of boxes, sometimes linked. */
export interface SequenceFrame {
  kind: "sequence";
  items: SequenceItem[];
  note: string;
  /** Labels pinned to an end, such as `top`, `front`, `rear`, `head`. */
  pins?: Record<number, string>;
  linked?: boolean;
  stats?: Record<string, number>;
}

/** A heap shown both ways at once, which is the whole point of a heap. */
export interface HeapFrame {
  kind: "heap";
  values: number[];
  roles: Record<number, Role>;
  note: string;
  stats?: Record<string, number>;
}

export interface BucketFrame {
  kind: "buckets";
  buckets: { key: string; items: string[]; role?: Role }[];
  note: string;
  stats?: Record<string, number>;
}

export interface GraphNode {
  id: string;
  label: string;
  /** Layout is computed by the generator, in viewBox units. */
  x: number;
  y: number;
  role?: Role;
  /** Shown under the node — a distance, a discovery time, a component id. */
  badge?: string;
}

export interface GraphEdge {
  from: string;
  to: string;
  weight?: number;
  role?: Role;
  directed?: boolean;
}

export interface GraphFrame {
  kind: "graph";
  nodes: GraphNode[];
  edges: GraphEdge[];
  note: string;
  stats?: Record<string, number>;
  /** An ordered list built as the algorithm runs — a traversal order, a path. */
  output?: string[];
}

/**
 * A table: a DP grid, a distance matrix, or a character grid.
 *
 * `cells` holds display strings rather than numbers because a DP table often
 * wants a blank for "not computed yet", which no number can honestly stand in
 * for.
 */
export interface MatrixFrame {
  kind: "matrix";
  cells: string[][];
  roles: Record<string, Role>;
  rowLabels?: string[];
  colLabels?: string[];
  note: string;
  stats?: Record<string, number>;
}

/**
 * One row of a project tree: a file or a directory, at some indent depth.
 *
 * Deliberately flat rather than nested, for the same reason `TreeNode` carries
 * its own `depth` and `x`: a frame has to be a complete, self-describing
 * snapshot, and a renderer that had to walk a nested structure to work out
 * indentation would be recomputing layout on every frame.
 */
export interface FileEntry {
  id: string;
  /** The base name. Directories carry their trailing slash in the name. */
  name: string;
  depth: number;
  kind: "dir" | "file";
  role?: Role;
  /** What this file is for, shown to the right of the name. */
  note?: string;
}

/**
 * A directory listing, which is what a folder-structure question is really
 * about.
 *
 * Drawn as an indented list rather than as a `TreeFrame`, because a project
 * layout is read the way `tree` prints it — every row is a path, and the
 * interesting comparison is between two *listings*, not between two graphs.
 */
export interface FileTreeFrame {
  kind: "filetree";
  entries: FileEntry[];
  /** The directory everything below is relative to, e.g. `my-app/`. */
  root?: string;
  note: string;
  stats?: Record<string, number>;
}

export type Frame =
  | ArrayFrame
  | TreeFrame
  | SequenceFrame
  | HeapFrame
  | BucketFrame
  | GraphFrame
  | MatrixFrame
  | FileTreeFrame;

/** Key for `MatrixFrame.roles`. */
export function cellKey(row: number, col: number): string {
  return `${row},${col}`;
}

/** Every generator returns this. */
export interface Visualisation {
  frames: Frame[];
  /** Shown under the player as the standing explanation. */
  summary: string;
}

/** Collects frames while an algorithm runs. */
export class Recorder<T extends Frame> {
  readonly frames: T[] = [];
  private counters: Record<string, number> = {};

  bump(name: string, by = 1) {
    this.counters[name] = (this.counters[name] ?? 0) + by;
  }

  get stats(): Record<string, number> {
    return { ...this.counters };
  }

  push(frame: Omit<T, "stats"> & { stats?: Record<string, number> }) {
    this.frames.push({ ...frame, stats: { ...this.counters } } as T);
  }
}
