import type { Lesson } from "@/content/types";

export const readingErrorsLesson: Lesson = {
  id: "cpp-reading-errors",
  slug: "reading-compiler-errors",
  moduleSlug: "foundations",
  title: "Reading Compiler & Linker Errors",
  summary:
    "The skill that determines how fast you learn C++: the six errors you will hit this week and what each really means, why the reported line is often not the broken one, and how to survive a 128-line template error.",
  estimatedMinutes: 30,
  objectives: [
    "Tell a compiler error from a linker error at a glance, and know what each implies",
    "Fix only the first error, then recompile",
    "Recognise the six most common beginner errors from their text",
    "Understand why the reported line is sometimes the line after the mistake",
    "Extract the one useful line from a template error wall",
    "Use the compiler's suggestions instead of skimming past them",
  ],
  sections: [
    {
      id: "strategy",
      heading: "Three rules before any specific error",
      body: [
        "**Fix the first error, then recompile.** C++ errors cascade violently: one unknown type can produce a dozen follow-on errors from code that is perfectly fine. The second error onward is often noise generated by the compiler's attempt to keep going after the first. Beginners scroll to the bottom; experienced programmers scroll to the top.",
        "**Read past the error line to the notes.** Modern GCC and Clang append `note:` lines that frequently contain the exact fix, including the characters to insert. Skimming to the red text and stopping means throwing away the most useful part of the message.",
        "**Know which tool is talking.** A compiler error names a file and a line and complains about syntax or types. A linker error mentions `ld`, names a *symbol*, and usually gives no line of yours at all. They have completely different causes, and misidentifying which you are looking at is the main reason people get stuck.",
      ],
      examples: [
        {
          id: "compiler-vs-linker",
          title: "The two shapes, side by side",
          lang: "bash",
          code: `# COMPILER — names your file and line, complains about the code itself.
main.cpp: In function 'int main()':
main.cpp:4:30: error: 'total' was not declared in this scope
    4 |     std::cout << "size: " << total << '\\n';
      |                              ^~~~~

# LINKER — mentions ld, names a symbol, gives no line of yours.
/usr/bin/ld: /tmp/cchB3Mfs.o: in function 'main':
main.cpp:(.text+0xa): undefined reference to 'square(int)'
collect2: error: ld returned 1 exit status`,
          explanation:
            "The linker message does mention `main.cpp`, but note what follows: `(.text+0xa)` is a byte offset into the machine code, not a line number. That is the tell. The linker has no idea what your source looked like — it is matching symbol names, and one of them has no definition anywhere.",
        },
      ],
    },
    {
      id: "off-by-one",
      heading: "The error is often on the line before",
      body: [
        "The single most confusing thing about C++ diagnostics for a newcomer: **a missing semicolon is reported on the following line.**",
        "The reason is mechanical. C++ statements end at `;`, so when you omit one the parser does not know the statement is finished. It keeps reading, pulls the next line into the same statement, and only realises something is wrong when the combination becomes impossible. By then it is pointing at the innocent line.",
        "The habit that fixes it: **when an error points at a line that looks fine, check the line above.** This applies to a missing semicolon after a class or struct definition too, which is a particularly nasty one because the error can appear many lines later.",
      ],
      examples: [
        {
          id: "missing-semicolon",
          title: "Line 4 is broken; line 5 is blamed",
          lang: "cpp",
          code: `#include <iostream>

int main() {
    int x = 5
    std::cout << x << '\\n';
}`,
          output: `error: expected ',' or ';' before 'std'
    5 |     std::cout << x << '\\n';
      |     ^~~`,
          explanation:
            "The message even tells you what it wanted — `expected ',' or ';'` — and where it wanted it: `before 'std'`, which is the start of line 5, meaning the end of line 4. Once you read it that way it is precise rather than misleading.",
        },
      ],
    },
    {
      id: "common-errors",
      heading: "The six you will actually hit",
      body: [
        "These cover the overwhelming majority of what a newcomer sees. Learn to recognise them by shape and you will stop needing to search for them.",
      ],
      examples: [
        {
          id: "not-declared",
          title: "1. 'X' was not declared in this scope",
          lang: "cpp",
          code: `#include <iostream>

int main() {
    std::cout << "size: " << total << '\\n';
}`,
          output: `error: 'total' was not declared in this scope
    4 |     std::cout << "size: " << total << '\\n';
      |                              ^~~~~`,
          explanation:
            "The name does not exist here. Causes, in order of likelihood: a typo, using a variable before its declaration, using a variable that is out of scope (declared inside a block that has ended), or a missing `std::` prefix.",
        },
        {
          id: "missing-include",
          title: "2. 'vector' is not a member of 'std'",
          lang: "cpp",
          code: `#include <iostream>

int main() {
    std::vector<int> scores{90, 80};
    std::cout << scores.size() << '\\n';
}`,
          output: `error: 'vector' is not a member of 'std'
    4 |     std::vector<int> scores{90, 80};
      |          ^~~~~~
note: 'std::vector' is defined in header '<vector>'; this is probably
      fixable by adding '#include <vector>'
    1 | #include <iostream>
  +++ |+#include <vector>

error: expected primary-expression before 'int'
error: 'scores' was not declared in this scope`,
          explanation:
            "**Look at the note — it names the header and shows you the line to add**, with `+++ |+` marking the insertion. And look at the cascade: one missing include produced three errors, of which only the first is real. This is rule one in action.",
        },
        {
          id: "type-mismatch",
          title: "3. cannot convert 'X' to 'Y'",
          lang: "cpp",
          code: `#include <string>

int main() {
    std::string s = "hi";
    int n = s;
}`,
          output: `error: cannot convert 'std::string' {aka 'std::__cxx11::basic_string<char>'} to 'int' in initialization
    4 |     int n = s;
      |             ^
      |             |
      |             std::string {aka std::__cxx11::basic_string<char>}`,
          explanation:
            "The `{aka ...}` is GCC expanding a type alias to its real name, which is verbose but occasionally the only way to see what a type actually is. Fixing this means an explicit conversion — here `std::stoi(s)` — rather than a cast, because a cast would simply silence a genuine incompatibility.",
        },
        {
          id: "undefined-reference",
          title: "4. undefined reference to 'square(int)'",
          lang: "cpp",
          code: `// math_utils.h
#pragma once
int square(int n);

// math_utils.cpp
#include "math_utils.h"
int square(int n) { return n * n; }

// main.cpp
#include "math_utils.h"
#include <iostream>
int main() { std::cout << square(7) << '\\n'; }`,
          output: `$ g++ -std=c++20 main.cpp -o app
/usr/bin/ld: in function 'main':
main.cpp:(.text+0xa): undefined reference to 'square(int)'
collect2: error: ld returned 1 exit status

$ g++ -std=c++20 main.cpp math_utils.cpp -o app     # compile both
$ ./app
49`,
          explanation:
            "**The most common linker error, and the fix is almost always \"you forgot to compile a file\".** The header promised `square` exists; `main.cpp` believed it; nobody supplied the definition because `math_utils.cpp` was never passed to the compiler. Other causes of the same message: declaring a function and never writing its body, or forgetting a library flag like `-lpthread`.",
        },
        {
          id: "no-main",
          title: "5. undefined reference to 'main'",
          lang: "bash",
          code: `$ g++ -std=c++20 math_utils.cpp -o lib
/usr/bin/ld: Scrt1.o: in function '_start':
(.text+0x17): undefined reference to 'main'
collect2: error: ld returned 1 exit status`,
          explanation:
            "You asked for an executable from files that contain no `main`. Either you meant to compile to an object file with `-c`, or you left `main.cpp` off the command line. `_start` is the real entry point supplied by the C runtime — it does setup and then calls your `main`, which is why *it* is the thing complaining.",
        },
        {
          id: "no-matching-function",
          title: "6. no matching function for call to …",
          lang: "cpp",
          code: `#include <concepts>
#include <iostream>

template <std::integral T>
T twice(T value) { return value * 2; }

int main() {
    std::cout << twice(21) << '\\n';
    std::cout << twice(3.5) << '\\n';   // double is not integral
}`,
          output: `error: no matching function for call to 'twice(double)'
    9 |     std::cout << twice(3.5) << '\\n';
      |                  ~~~~~^~~~~
note: candidate: 'template<class T>  requires  integral<T> T twice(T)'
note:   template argument deduction/substitution failed:
note: constraints not satisfied`,
          explanation:
            "A function with that name exists, but none of the overloads accept these arguments. **The `note: candidate:` lines are the valuable part** — they list what the compiler *did* find, so you can compare it against what you passed. Here the candidate requires `std::integral` and `double` is not, which the last note states directly.",
        },
      ],
    },
    {
      id: "template-walls",
      heading: "Surviving a template error",
      body: [
        "This is the reputation-defining C++ experience, and it is worth confronting once so it stops being frightening.",
        "Sorting a `std::vector<Point>` where `Point` has no `operator<` produces **128 lines of output from GCC** — and 220 from Clang, which is a useful corrective to the belief that Clang is always kinder.",
        "The reason for the volume is that the error is discovered deep inside the standard library, after several layers of template instantiation, and the compiler dutifully reports the whole chain that got there. Almost all of it is the path, not the problem.",
        "**The technique: search the output for the first line containing `error:`, and read only that.** In the 128-line wall below it is line 20, and it says exactly what is wrong in one sentence.",
      ],
      examples: [
        {
          id: "template-wall",
          title: "128 lines with one line that matters",
          lang: "cpp",
          code: `#include <algorithm>
#include <vector>

struct Point { int x, y; };

int main() {
    std::vector<Point> pts{{1, 2}, {3, 4}};
    std::sort(pts.begin(), pts.end());   // Point has no operator<
}`,
          output: `$ g++ -std=c++20 sortpoints.cpp 2>&1 | wc -l
128

$ g++ -std=c++20 sortpoints.cpp 2>&1 | grep -m1 "error:"
predefined_ops.h:45:23: error: no match for 'operator<'
                        (operand types are 'Point' and 'Point')`,
          explanation:
            "One sentence: `Point` cannot be compared with `<`. The fix is one line — `auto operator<=>(const Point&) const = default;` — and everything else in those 128 lines was the compiler showing its work. **Keep `2>&1 | grep -m1 \"error:\"` in your muscle memory**; `-fmax-errors=1` on GCC and `-ferror-limit=1` on Clang do a similar job by stopping after the first.",
        },
      ],
      pitfalls: [
        {
          title: "C++20 concepts exist substantially to fix this",
          body: "Compare the 128 lines above with the 18 lines the constrained `twice` template produced. The difference is *where* the failure is detected: a concept states the requirement at the function's boundary, so the compiler rejects the call immediately and reports it against your code. Without one, the failure happens deep inside an instantiation and the diagnostic has to describe that whole journey. This is the main practical reason to write concepts on your own templates, covered in module 7.",
        },
      ],
    },
    {
      id: "warnings",
      heading: "Warnings are errors you have not hit yet",
      body: [
        "C++ compilers are quiet by default about a long list of things that are almost certainly bugs. Everything in this section only appears if you asked for it.",
        "Warnings you have already met in this module: `-Wuninitialized` (reading an uninitialised variable), `-Wvexing-parse` (a declaration that looks like a construction), `-Wsequence-point` (modifying a variable twice in one expression), `-Wparentheses` (precedence you probably did not intend), `-Wsign-compare` (comparing signed with unsigned). **Every one of those is a real bug, and every one compiles silently without the flags.**",
        "The baseline to adopt now: `-Wall -Wextra`. Two additions worth considering as you get comfortable: `-Wshadow` (an inner variable hiding an outer one) and `-Wconversion` (implicit conversions that lose data, though this one is noisy in existing code).",
        "Once a project builds cleanly, `-Werror` turns warnings into errors so the state cannot regress. That belongs in CI rather than in your local build, where a warning mid-refactor is useful information and not a reason to stop.",
      ],
      examples: [
        {
          id: "warning-flags",
          title: "What to actually put in your build",
          lang: "bash",
          code: `# Day-to-day.
$ g++ -std=c++20 -Wall -Wextra -g -O0 main.cpp -o app

# When hunting a bug you cannot reproduce.
$ g++ -std=c++20 -Wall -Wextra -g -fsanitize=address,undefined main.cpp -o app

# In CI, once the project is clean.
$ g++ -std=c++20 -Wall -Wextra -Wshadow -Werror main.cpp -o app

# The second opinion. Costs one command; catches things the other missed.
$ clang++ -std=c++20 -Wall -Wextra main.cpp -o app`,
          explanation:
            "The last one is genuinely worth doing periodically. GCC and Clang disagree about which mistakes deserve a warning, and about the wording, so a file that is clean under both has been checked twice by two different implementations. On the template error earlier, GCC produced 128 lines and Clang 220 — but on other errors Clang's message is dramatically clearer, and it costs nothing to look.",
        },
      ],
    },
  ],
  interviewQuestions: [
    {
      question: "How do you tell a compiler error from a linker error?",
      answer:
        "A compiler error names one of your files and a line number and complains about syntax or types within a single translation unit. A linker error mentions `ld`, names a symbol like `square(int)` or `main`, and typically gives a byte offset such as `(.text+0xa)` rather than a line. The distinction matters because the causes are completely different: a compiler error means the code is wrong, while a linker error usually means a definition is missing — a `.cpp` file that was never compiled, a declared function that was never defined, or a missing library flag.",
    },
    {
      question: "Why is a missing semicolon reported on the following line?",
      answer:
        "Because statements are terminated by `;`, so without one the parser does not know the statement has ended. It continues reading, absorbs the next line into the same statement, and only detects the problem when the combination becomes impossible — by which point it is pointing at the line after the mistake. The habit is: when an error points at a line that looks correct, check the line above. It is especially nasty after a class or struct definition, where the error can surface much further down.",
    },
    {
      question: "You get 128 lines of template errors. How do you approach it?",
      answer:
        "Find the first line containing `error:` and read only that; everything else is the instantiation path the compiler took to reach the failure. `2>&1 | grep -m1 \"error:\"` does it, and `-fmax-errors=1` or Clang's `-ferror-limit=1` stops after the first. In one real case, 128 lines of output reduced to a single sentence — that `Point` had no `operator<` — with a one-line fix. C++20 concepts exist substantially to reduce this, because a constraint is checked at the function boundary and reported against your call rather than deep inside a library instantiation.",
    },
    {
      question: "Why should you fix only the first error and recompile?",
      answer:
        "Errors cascade. A single unknown type or missing include can produce a dozen follow-on errors from code that is entirely correct — a missing `#include <vector>` typically produces three, of which only the first is real. Everything after the first is the compiler's attempt to continue parsing in a state it should not be in, so most of it disappears when you fix the original. Reading top-down rather than bottom-up is the difference between one edit and a confusing hunt.",
    },
    {
      question: "Which compiler warnings do you turn on, and why?",
      answer:
        "`-Wall -Wextra` as a baseline, adding `-Wshadow` and considering `-Wconversion`. Every warning in that set corresponds to a real bug class that otherwise compiles silently: reading an uninitialised variable, the most vexing parse, modifying a variable twice in one expression, unintended operator precedence, and signed/unsigned comparison. `-Werror` belongs in CI so a clean project cannot regress, but not in a local build where a warning mid-refactor is useful rather than blocking. Building occasionally with a second compiler catches more still, since GCC and Clang disagree about what is worth warning about.",
    },
  ],
  takeaways: [
    "Fix the first error and recompile — the rest are usually cascade noise",
    "Read past `error:` to the `note:` lines; they often contain the exact fix, insertion marker included",
    "Compiler errors name a file and line; linker errors name a symbol and a byte offset",
    "A missing semicolon is reported on the *next* line — when a line looks fine, check the one above",
    "\"undefined reference to X\" almost always means a `.cpp` file was not compiled or a body was never written",
    "For a template error wall, `grep -m1 \"error:\"` finds the one line that matters",
    "`-Wall -Wextra` is the minimum; every warning in it corresponds to a real bug that compiles silently without it",
    "Build with a second compiler occasionally — they disagree about what is worth reporting",
  ],
  status: "available",
};
